package com.lifequest.recommendation;
import com.lifequest.common.exception.*;import com.lifequest.recommendation.dto.*;import java.util.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.stereotype.Service;
@Service
public class QuestRecommendationService {
 private final RoutingQuestRecommendationProvider provider;private final QuestRecommendationPromptFactory prompts;private final QuestRecommendationValidator validator;private final QuestRecommendationUsageService usage;
 public QuestRecommendationService(RoutingQuestRecommendationProvider provider,QuestRecommendationPromptFactory prompts,QuestRecommendationValidator validator,QuestRecommendationUsageService usage){this.provider=provider;this.prompts=prompts;this.validator=validator;this.usage=usage;}
 public QuestRecommendationResponse place(Long userId,PlaceQuestRecommendationRequest r){validatePlace(r);return generate(userId,RecommendationType.PLACE,prompts.place(r),new RecommendationConstraints(RecommendationType.PLACE,r.budgetPerPerson(),r.availableMinutes()));}
 public QuestRecommendationResponse travel(Long userId,TravelQuestRecommendationRequest r){validateTravel(r);return generate(userId,RecommendationType.TRAVEL,prompts.travel(r),new RecommendationConstraints(RecommendationType.TRAVEL,r.budgetPerPerson(),r.days()));}
 private QuestRecommendationResponse generate(Long userId,RecommendationType type,String prompt,RecommendationConstraints constraints){LlmProvider selected=provider.selected();String model=provider.model();int remaining;try{remaining=usage.consume(userId);}catch(DataIntegrityViolationException first){remaining=usage.consume(userId);}List<QuestRecommendationCandidate> result=provider.generate(type,QuestRecommendationPromptFactory.SYSTEM_INSTRUCTION,prompt);return new QuestRecommendationResponse(selected,model,remaining,validator.validate(result,constraints));}
 private void validatePlace(PlaceQuestRecommendationRequest r){if(r==null||invalidText(r.area(),2,100)||r.availableMinutes()==null||r.availableMinutes()<30||r.availableMinutes()>720||r.budgetPerPerson()==null||r.budgetPerPerson()<0||r.budgetPerPerson()>10000000||r.companionCount()==null||r.companionCount()<1||r.companionCount()>20||r.environment()==null)invalid();common(r.interests(),r.additionalRequest());}
 private void validateTravel(TravelQuestRecommendationRequest r){if(r==null||invalidText(r.destination(),2,100)||r.days()==null||r.days()<1||r.days()>14||r.budgetPerPerson()==null||r.budgetPerPerson()<0||r.budgetPerPerson()>50000000||r.companionCount()==null||r.companionCount()<1||r.companionCount()>20)invalid();common(r.interests(),r.additionalRequest());}
 private void common(List<String> interests,String request){if(interests!=null&&(interests.size()>5||interests.stream().anyMatch(i->invalidText(i,1,30)))||request!=null&&request.trim().length()>500)invalid();}
 private boolean invalidText(String v,int min,int max){return v==null||v.trim().length()<min||v.trim().length()>max;}private void invalid(){throw new BusinessException(ErrorCode.VALIDATION_FAILED);}
}
