import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const OUT='C:/workspace/LifeQuest/LifeQuest_Technical_Specification_Final.pptx';
const A='C:/workspace/LifeQuest/.codex-ppt/assets';
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={green:'#55663D',deep:'#3F5030',ink:'#443B2A',body:'#5C5344',muted:'#7A7060',cream:'#FEF8EE',paper:'#FFFDF6',tint:'#FBF4E4',tile:'#F3E9D0',gold:'#E7B94F',terr:'#C96A47',sage:'#8FA86A',lav:'#9C87B5',line:'#D8CDB4'};
const F='Arial';
function shape(s,x,y,w,h,fill=C.paper,line=C.line,r='roundRect'){const cfg={geometry:r,position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:line,width:1}};if(r==='rect'||r==='textbox'||r==='roundRect')cfg.borderRadius='rounded-xl';return s.shapes.add(cfg);}
function text(s,v,x,y,w,h,fs=19,color=C.ink,bold=false,align='left'){const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});q.text=v;q.text.style={fontFamily:F,fontSize:fs,color,bold,alignment:align,verticalAlignment:'middle'};return q;}
function slide(n,title,k='TECHNICAL SPECIFICATION'){const s=p.slides.add();s.background.fill=C.cream;text(s,k,64,28,640,24,13,C.terr,true);text(s,title,64,58,1110,62,39,C.deep,true);text(s,String(n).padStart(2,'0'),1160,35,56,26,15,C.muted,true,'right');text(s,'LifeQuest | Technical Specification',64,682,430,18,11,C.muted);return s;}
async function img(s,name,x,y,w,h,fit='contain',radius='rounded-xl'){const b=await fs.readFile(`${A}/${name}`);return s.images.add({blob:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),contentType:'image/png',alt:name,fit,position:{left:x,top:y,width:w,height:h},geometry:'roundRect',borderRadius:radius});}
async function phone(s,name,x,y,h=510){const w=h*417/930;shape(s,x-10,y-10,w+20,h+20,C.ink,C.ink);shape(s,x-4,y-4,w+8,h+8,C.paper,C.paper);await img(s,name,x,y,w,h,'cover');return w;}
function chip(s,v,x,y,w,fill=C.green,color=C.paper){shape(s,x,y,w,36,fill,fill);text(s,v,x,y,w,36,14,color,true,'center');}
function card(s,x,y,w,h,t,b,accent=C.green){shape(s,x,y,w,h,C.paper,C.line);shape(s,x,y,8,h,accent,accent,'rect');text(s,t,x+24,y+14,w-42,34,23,C.deep,true);text(s,b,x+24,y+52,w-42,h-64,18,C.body);}
function arrows(s,items,y){let x=70;items.forEach((v,i)=>{const w=Math.max(130,Math.min(210,v.length*12+40));if(i)text(s,'→',x-30,y,30,48,24,C.terr,true,'center');shape(s,x,y,w,48,i===items.length-1?C.green:C.paper,i===items.length-1?C.green:C.line);text(s,v,x+8,y,w-16,48,16,i===items.length-1?C.paper:C.ink,true,'center');x+=w+30;});}
function spec(s,x,y,w,title,lines){text(s,title,x,y,w,30,22,C.deep,true);text(s,lines.map(v=>'• '+v).join('\n'),x,y+38,w,lines.length*30+10,18,C.body);}

// 1 Cover
{const s=p.slides.add();s.background.fill=C.deep;shape(s,0,0,1280,720,C.deep,C.deep,'rect');shape(s,760,-90,600,900,C.green,C.green,'ellipse');shape(s,920,72,250,520,C.paper,C.paper);await img(s,'spec-main.png',934,88,222,488,'cover');await img(s,'logo-char.png',730,445,155,155,'contain');chip(s,'PROJECT TECHNICAL SPECIFICATION',70,95,330,C.gold,C.ink);text(s,'LIFE\nQUEST',70,150,620,190,70,C.paper,true);text(s,'일상을 퀘스트로 만들고\n기록을 성장으로 연결한다',74,360,570,92,28,'#F3E9D0',true);text(s,'Flutter · React · Spring Boot · MySQL · JWT · AI · GPS',74,500,650,38,19,'#D8DFC5');text(s,'TECHNICAL SPECIFICATION  /  2026',74,642,560,22,12,'#BFC9A9',true);}
// 2-7 framing
{const s=slide(2,'행동–보상–기록이 이어지는 현실 RPG');[['QUEST','일간·주간·지역·그룹'],['GROWTH','EXP·레벨·보상'],['COLLECTION','업적·칭호·도감'],['SOCIAL','친구·그룹·랭킹'],['LOCATION','GPS 위치 검증'],['AI','장소·여행 추천']].forEach((v,i)=>card(s,66+(i%3)*382,160+Math.floor(i/3)*210,350,176,v[0],v[1],[C.green,C.gold,C.terr,C.sage,C.lav,C.deep][i]));}
{const s=slide(3,'체크리스트를 새로운 경험의 성장 루프로 전환');card(s,70,170,350,350,'기존 방식','할 일을 직접 등록하고 반복 체크합니다. 완료 이후의 성장감과 새로운 행동 발견이 약합니다.',C.muted);text(s,'→',440,300,70,60,38,C.terr,true,'center');card(s,530,170,650,350,'LifeQuest','새로운 장소·활동을 퀘스트로 제안하고, 완료 결과를 EXP·레벨·업적·도감으로 연결합니다.',C.green);arrows(s,['현실 행동','퀘스트 완료','성장','수집'],565);}
{const s=slide(4,'프로젝트의 네 가지 개발 원칙');[['직관적 경험','설명 없이도 도전→수행→보상을 이해'],['기능 간 연결','완료 이벤트가 여러 성장 도메인에 반영'],['실제 데이터 구조','UI·API·DB가 같은 규칙으로 동작'],['확장 가능한 도메인','추천·지역·소셜 기능을 독립 확장']].forEach((v,i)=>card(s,70+(i%2)*570,170+Math.floor(i/2)*220,540,190,`${String(i+1).padStart(2,'0')}  ${v[0]}`,v[1],[C.green,C.gold,C.terr,C.sage][i]));}
{const s=slide(5,'핵심 기능은 하나의 성장 경험을 분담한다');arrows(s,['QUEST','EXP / LEVEL','REWARD','ACHIEVEMENT','LIFEDEX'],190);arrows(s,['FRIEND','GROUP','RANKING','NOTIFICATION'],300);arrows(s,['AI RECOMMEND','GPS VERIFY','ADMIN'],410);text(s,'사용자 행동을 시작시키는 기능과, 완료 결과를 축적하는 기능을 하나의 서비스 흐름으로 연결했습니다.',85,540,1110,58,24,C.deep,true,'center');}
{const s=slide(6,'앱과 관리자 웹은 하나의 도메인 규칙을 공유한다');text(s,'CLIENT',80,160,200,28,16,C.terr,true);card(s,80,198,270,160,'Flutter App','Riverpod · GoRouter\n사용자 행동과 상태 표현',C.green);card(s,80,380,270,140,'React Admin','운영 데이터와 카탈로그 관리',C.gold);text(s,'→  REST / JSON  →',378,302,220,44,20,C.terr,true,'center');card(s,620,190,290,340,'Spring Boot','Controller\nSpring Security / JWT\nDomain Service\nRepository / JPA',C.terr);text(s,'→',928,302,55,44,28,C.terr,true,'center');card(s,1000,228,210,190,'MySQL','Flyway migration\n관계형 도메인 데이터',C.deep);text(s,'요청 흐름  |  Flutter → REST API → Security → Service → JPA → MySQL → DTO → 화면 상태',80,570,1130,52,21,C.deep,true,'center');}
{const s=slide(7,'사용자를 중심으로 퀘스트·성장·소셜 데이터가 연결된다');[['USER','User · Character · SocialAccount'],['QUEST','Quest · UserQuest · QuestProof'],['GROWTH','ExpLog · LevelReward · RewardGrant'],['COLLECTION','Achievement · Title · Lifedex'],['SOCIAL','Friendship · Group · GroupQuest'],['SYSTEM','Notification · Region · Location']].forEach((v,i)=>card(s,70+(i%3)*380,160+Math.floor(i/3)*205,350,175,v[0],v[1],[C.green,C.gold,C.terr,C.sage,C.lav,C.deep][i]));}
// screenshots journey
{const s=slide(8,'홈은 오늘의 퀘스트와 성장 상태를 한 화면에 모은다','USER JOURNEY · HOME');await phone(s,'spec-main.png',82,145,500);spec(s,390,165,760,'화면 목적',['접속 직후 현재 레벨과 오늘의 행동 확인','퀘스트 상세·알림·하단 메뉴로 빠르게 이동']);spec(s,390,315,760,'데이터 처리',['홈 조회 API가 사용자 성장과 할당 퀘스트를 반환','Riverpod 상태 갱신 후 EXP·퀘스트 목록을 동시 반영']);chip(s,'행동 → API 요청 → 상태 저장 → UI 반영',390,535,560,C.green);}
{const s=slide(9,'퀘스트 탐색과 AI 추천을 한 여정으로 통합','USER JOURNEY · DISCOVER');await phone(s,'spec-quests.png',55,170,430);await phone(s,'spec-quest-list-week.png',360,170,430);await phone(s,'spec-recommend.png',665,170,430);spec(s,970,185,250,'통합 범위',['일간·주간 목록','AI 장소/여행 추천','선택 후 상세 이동']);text(s,'Quest API\n+ Recommendation API\n+ UserQuest 상태',970,365,250,110,20,C.deep,true,'center');chip(s,'발견 → 선택 → 등록',970,520,230,C.terr);}
{const s=slide(10,'완료 이벤트가 보상과 레벨업을 연쇄 처리한다','USER JOURNEY · COMPLETE');await phone(s,'spec-quest-completed.png',110,155,475);await phone(s,'spec-levelup-popup.png',450,155,475);spec(s,810,170,380,'처리 순서',['완료 조건 검증','UserQuest 상태 변경','EXP 기록 및 레벨 계산','보상·업적·도감 평가','최종 결과 DTO 반환']);chip(s,'단일 트랜잭션',810,500,220,C.terr);text(s,'중복 요청에도 보상은 한 번만 지급',810,550,380,40,20,C.deep,true);}
{const s=slide(11,'업적·도감·캐릭터가 성장의 결과를 시각화한다','USER JOURNEY · GROWTH');await phone(s,'spec-achievements.png',45,175,420);await phone(s,'spec-dogam.png',340,175,420);await phone(s,'spec-ch.png',635,175,420);spec(s,930,190,275,'연결 데이터',['Achievement 진행률','UserLifedex 수집률','Character / Accessory','대표 칭호']);text(s,'퀘스트 완료 결과가\n“숫자”에서\n“소유한 경험”으로 바뀝니다.',930,400,275,120,23,C.deep,true,'center');}
{const s=slide(12,'친구와 그룹은 개인 퀘스트를 공동 경험으로 확장한다','USER JOURNEY · SOCIAL');await phone(s,'spec-friends.png',90,165,470);await phone(s,'spec-group.png',425,165,470);spec(s,790,180,400,'주요 기능',['친구 요청·EXP 랭킹','그룹 퀘스트 참여','진행 상태와 공동 보상','소유권·멤버 권한 검증']);arrows(s,['친구 발견','그룹 참여','공동 완료'],525);}
{const s=slide(13,'마이페이지는 성장 기록과 개인 설정의 허브다','USER JOURNEY · PROFILE');await phone(s,'spec-mypage.png',110,150,500);spec(s,470,165,700,'표현 정보',['캐릭터·액세서리·대표 칭호','레벨·EXP·완료 퀘스트','업적·도감·친구']);spec(s,470,360,700,'갱신 원칙',['프로필 PATCH 후 사용자 상태 캐시 무효화','친구·그룹·랭킹 화면에 동일 정보 재반영']);chip(s,'Single Source of Profile State',470,535,420,C.green);}
{const s=slide(14,'관리자 웹은 운영 현황과 콘텐츠 변경을 담당한다','ADMIN CONSOLE');shape(s,70,155,1140,395,C.ink,C.ink);await img(s,'spec-admin.png',78,163,1124,379,'cover');text(s,'Admin Web → REST API → Admin Service → Database → User App 재조회',90,580,1100,42,22,C.deep,true,'center');}
// technical details
{const s=slide(15,'화면과 서버는 역할을 분리해 변경 영향을 줄인다');[['Presentation','화면과 사용자 이벤트'],['Application State','Riverpod provider / controller'],['API Client','DTO 직렬화·토큰 전달'],['Controller','요청 검증·응답 경계'],['Domain Service','완료·성장·권한 규칙'],['Repository','JPA 영속성']].forEach((v,i)=>card(s,70+(i%3)*380,160+Math.floor(i/3)*205,350,175,v[0],v[1],[C.green,C.gold,C.terr,C.sage,C.lav,C.deep][i]));}
{const s=slide(16,'퀘스트 완료는 처리 순서와 트랜잭션이 핵심이다');arrows(s,['사용자·퀘스트 확인','조건 검증','UserQuest 완료','EXP 기록'],190);arrows(s,['레벨 계산','보상 지급','업적 평가','도감 갱신'],310);arrows(s,['GrowthResult 조합','DTO 반환','Provider 갱신','결과 화면'],430);text(s,'부분 성공을 허용하지 않는 하나의 완료 단위',160,560,960,50,25,C.deep,true,'center');}
{const s=slide(17,'JWT와 역할 기반 인가가 데이터 접근 경계를 만든다');arrows(s,['Login','자격 검증','JWT 발급','Token 저장'],190);arrows(s,['API 요청','Security 인증','사용자 식별','소유권 검증'],310);arrows(s,['USER / ADMIN','도메인 접근','응답'],430);text(s,'클라이언트가 보낸 userId보다 인증 컨텍스트를 신뢰합니다.',130,560,1020,48,24,C.deep,true,'center');}
{const s=slide(18,'위치 인증은 클라이언트 권한과 서버 검증을 분리한다');arrows(s,['위치 권한 확인','좌표 취득','questId + 좌표 전송'],205);arrows(s,['목표 좌표 조회','거리 계산','반경 조건 검증','완료 처리'],345);card(s,190,500,900,105,'신뢰 경계','앱은 권한과 위치를 수집하고, 서버가 최종 완료 조건을 판단합니다.',C.lav);}
{const s=slide(19,'운영 변경은 기록을 보존하면서 신규 사용자 경험에 반영한다');arrows(s,['Admin Quest 수정','권한 검증','Catalog 저장'],210);arrows(s,['사용자 앱 재조회','신규 할당 반영','기존 완료 기록 보존'],350);text(s,'카탈로그 정의와 사용자 수행 이력을 분리해 운영 안정성을 확보했습니다.',130,525,1020,60,24,C.deep,true,'center');}
{const s=slide(20,'세 가지 문제를 서비스 경계로 해결했다');card(s,70,155,540,145,'성장 데이터 일관성','완료 서비스의 트랜잭션과 중복 방지 규칙으로 해결',C.terr);card(s,670,155,540,145,'다중 클라이언트','앱·관리자 웹의 단일 REST API 진입점으로 해결',C.green);card(s,70,340,540,145,'위치 예외 상황','권한 확인과 서버 거리 검증의 책임 분리로 해결',C.lav);card(s,670,340,540,145,'협업 충돌','공통 DTO·API 계약·Flyway 마이그레이션으로 해결',C.gold);text(s,'기능 수보다 경계와 연결 규칙이 프로젝트 완성도를 결정했습니다.',130,550,1020,50,24,C.deep,true,'center');}
{const s=slide(21,'프로젝트를 통해 전체 데이터 흐름을 이해했다');[['기능 간 연결','완료 하나가 성장·수집·소셜 데이터에 주는 영향을 추적했습니다.'],['클라이언트–서버','사용자 행동부터 DB와 다시 화면 반영까지 전 과정을 구현했습니다.'],['협업 기준','API 계약과 데이터 구조를 팀의 공통 언어로 사용했습니다.']].forEach((v,i)=>card(s,90+i*390,185,350,310,v[0],v[1],[C.green,C.terr,C.gold][i]));}
{const s=slide(22,'LifeQuest는 행동을 성장으로 연결하는 하나의 시스템이다');arrows(s,['Flutter App','REST API','Spring Boot','JPA / MySQL'],190);arrows(s,['QUEST','GROWTH','COLLECTION','SOCIAL'],320);arrows(s,['AI','GPS','ADMIN','JWT'],450);text(s,'현실의 행동을 퀘스트로 만들고, 퀘스트의 기록을 사용자의 성장으로 연결한다.',80,585,1120,46,25,C.deep,true,'center');}
const pptx=await PresentationFile.exportPptx(p);await pptx.save(OUT);console.log('slides',p.slides.items.length,OUT);
