INSERT INTO titles (code, name, description, acquire_type) VALUES
    ('QUEST_FIRST_STEP', '오늘을 연 모험가', '첫 퀘스트를 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_DAILY_10', '일상을 깨우는 자', '퀘스트를 10회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_30', '삼십 번의 작심가', '퀘스트를 30회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_100', '현생 만렙러', '퀘스트를 100회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_LOCATION_5', '골목의 나침반', '위치 인증 퀘스트를 5회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_LOCATION_15', '서울을 읽는 발걸음', '위치 인증 퀘스트를 15회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_SELF_REPORT_10', '작심을 현실로', '직접 완료 퀘스트를 10회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_WEEKLY_5', '칠일의 설계자', '주간 퀘스트를 5회 완료하면 획득합니다.', 'QUEST'),
    ('QUEST_LEGENDARY_1', '전설에 먼저 닿은 자', '전설 등급 퀘스트를 처음 완료하면 획득합니다.', 'QUEST'),
    ('LIFEDEX_FIRST_PAGE', '기억의 첫 페이지', '도감 항목을 처음 수집하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_5', '경험 수집가', '도감 항목을 5개 수집하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_10', '도시의 채집가', '도감 항목을 10개 수집하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_COMPLETE', '서울 생활대백과', '현재 도감의 모든 항목을 수집하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_CAFE_COMPLETE', '골목 카페 감별사', '카페 도감을 완성하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_PARK_COMPLETE', '도심의 숨을 아는 자', '공원·산책로 도감을 완성하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_CULTURE_COMPLETE', '전시장의 시간여행자', '문화·전시 도감을 완성하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_MARKET_COMPLETE', '골목 경제학자', '시장·골목 도감을 완성하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_NATURE_COMPLETE', '서울의 능선 수집가', '산·하천 도감을 완성하면 획득합니다.', 'LIFEDEX'),
    ('LIFEDEX_HISTORY_COMPLETE', '시간의 문지기', '역사·명소 도감을 완성하면 획득합니다.', 'LIFEDEX');
