spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
